apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: todo-api
        envFrom:
        - configMapRef:
            name: todo-config 
